### ISSUE TITLE
How does the scaling really work?

### ISSUE THREAD

**Issue by asyncanup** [limikael/pixiapp#1]
Does it,
- scale the application's container element with CSS scale() and then change the masking to show the right contents?
- something else?

**Comment by limikael** [comment]
The scaling and masking is done using PIXI.

The masking, which is optional and controlled by the matte and matteColor properties (http://limikael.altervista.org/pixiappdoc/classes/PixiApp.html#property_matte) is not actually a mask, but something that is drawn on top of the content.

The scaling is simply done in PIXI as a common scaling using scale.x and scale.y. The amount to scale is calculated based on two things. First the size of the window (if it is attached to the whole window) or the element containing the app. Second the logic size of the app. The "logic size" is the size that gets passed to the constructor. The scaling is calculated so that the app "fits" in the best way to the containing element.

The above is how the primary scaling is done. There is also another type of scaling done in css, which is controlled by the superSampling property (http://limikael.altervista.org/pixiappdoc/classes/PixiApp.html#property_superSampling). This, however, should not be seen as scaling, but a way to enhance the quality of the rendered content.

**Comment by limikael** [comment]
Does this clear up the issue? I.e. can I close?

**Comment by asyncanup** [comment]
Yes
